### ISSUE TITLE
Add command to output headers

### ISSUE THREAD

**Issue by joostdevries** [rwjblue/ember-cli-content-security-policy#11]
It would be great if we could add a `csp-headers` command to `ember` to make copying the CSP-headers ridiculously easy. So I could just do:

```
ember csp-headers --environment production
```

And get the right headers for my production environment.

**Comment by ZebraFlesh** [comment]
It's sort of easy and sort of not: you can already look at any request and see the exact headers used in development. The not so easy part is you need to replace localhost/127.0.0.1 with your production server. Plus the format in which you specify them depends upon your web server. It's easy to spit out some JSON and pull it into node/express, but is that really what IIS wants, for example? (I don't know?)

**Comment by alexgb** [comment]
:+1: This could allow deployment tools such as the [ember cli heroku buildpack](https://github.com/tonycoco/heroku-buildpack-ember-cli) to set the proper headers in production. 

Curious how others use this in production. It's unsettling that this addon only seems to support the ember cli development server and doesn't have a deployment story. I have a suspicion that this provides a false sense of security to many users who assume standard deployments support the CSP policies they've setup in `config/environment.js` when in fact they do not.

**Comment by sandstrom** [comment]
@joostdevries would this PR solve your issue? https://github.com/rwjblue/ember-cli-content-security-policy/pull/41 (I think it might :smile:)
