### ISSUE TITLE
Docs don't match released version

### ISSUE THREAD

**Issue by mfeckie** [rwjblue/ember-cli-content-security-policy#111]
The README currently refers to `config/content-security-policy.js`, but having recently installed this addon and having problems with config not being detected, I dug around and found that the installed version `1.1.1` doesn't include the new code required to read from the config file.

**Comment by jelhan** [comment]
Yeah, sorry. We are in the middle of a refactoring of the configuration. Please refer to readme for the version used. E.g. you could access the readme for v1.1 with this link: https://github.com/rwjblue/ember-cli-content-security-policy/blob/v1.1.1/README.md

**Comment by rwwagner90** [comment]
Is there an ETA on a new release? I just hit this issue as well.

**Comment by jelhan** [comment]
> Is there an ETA on a new release? I just hit this issue as well.

We are planing to do a first release candidate soon. See #100 for details.

**Comment by wongpeiyi** [comment]
Got hit by this as well. Maybe adding a note in the readme would help

**Comment by jelhan** [comment]
Closing as v2.0.0 has been released finally.
