### ISSUE TITLE
Cannot use direct output from ember csp-headers command

### ISSUE THREAD

**Issue by JCBarry** [rwjblue/ember-cli-content-security-policy#112]
In trying to configure my server for the CSP headers, I'd like to be able to run the `ember csp-headers` command to populate an environment variable with the correct header value.

However, because of the information text included at the beginning of the command output, I cannot use this output directly.

I believe a simple option, such as `raw` or `direct` when flagged to true, will simply output the policy result.

**Comment by JCBarry** [comment]
My present workaround is:
```
ember csp-headers | grep default
```

**Comment by rwjblue** [comment]
Hmm, I think we fixed this on master (but unreleased).

**Comment by jelhan** [comment]
Yes, master supports a `--silent` flag. See #84 for details.

**Comment by JCBarry** [comment]
Awesome, thanks!
