### ISSUE TITLE
Change connect-src in runtime

### ISSUE THREAD

**Issue by YD1722** [rwjblue/ember-cli-content-security-policy#114]
Can we change connect-src at runtime?

**Comment by sandstrom** [comment]
While the JS/Ember app is running?

CSP is delivered via a meta or header. Definitely not with the header method, but 99% sure it won't work with meta either. You can dig into the spec if you're curious, should be answered there.

https://www.w3.org/TR/CSP3/

I'm closing this now, but I'm willing to reopen if there is an actual code issue. If so, steps to reproduce (and ideally a failing test-case) is a good start.
