### ISSUE TITLE
Add report-uri http://localhost:4200

### ISSUE THREAD

**Issue by joostdevries** [rwjblue/ember-cli-content-security-policy#12]
Chrome throws additional errors when the CSP is active in Report-only mode but no report-uri is configured. 

I think adding `report-uri http://localhost:4200` to the CSP header would be fine for now.

Later on, we could add a blueprint for the server where we actually process the CSP reports.

**Comment by ZebraFlesh** [comment]
It looks like this was merged into master, but has not been released (judging by the 0.3.0 release which is fetched via npm). Could you please release it?
