### ISSUE TITLE
Disable CSP

### ISSUE THREAD

**Issue by givanse** [rwjblue/ember-cli-content-security-policy#14]
After installing the addon I noticed a slight delay in the Developer tools console. The page auto-loads as fast as usual, but the console remains in white-screen for about a second (maybe less).

It would be good to have an option, maybe in `contentSecurityPolicyHeader`, that turns it off.

**Comment by marclundgren** [comment]
@rwjblue I have a valid use case where I need to conditionally disable the package for a specific environment (development). Would you reconsider adding in an optional `disabled` flag?

**Comment by sandstrom** [comment]
@marclundgren You can set the `contentSecurityPolicy` to `null`. See https://github.com/rwjblue/ember-cli-content-security-policy/blob/master/index.js#L93

**Comment by marclundgren** [comment]
+1 thanks for the tip @sandstrom
