### ISSUE TITLE
In test mode frame-src settings are overwritten

### ISSUE THREAD

**Issue by chbonser** [rwjblue/ember-cli-content-security-policy#151]
### Reproduction Steps
- Install `2.0.0-1`
- In `config/content-security-policy.js` return the following object:
```js
  {
    delivery: ["meta"],
    enabled: true,
    failTests: true,
    policy: {
      "frame-src": ["data:"]
    }
  }
```

### Expected
Inspect the index.html generated during test and see the test configuration appended to my config: `frame-src data: 'self';`

### Actual
The index.html overwrites my config: `frame-src 'self';`

**Comment by jelhan** [comment]
Should be fixed by #152.
