### ISSUE TITLE
Setup Prettier

### ISSUE THREAD

**Issue by jelhan** [rwjblue/ember-cli-content-security-policy#157]
Prettier should be used. Setup should follow the description given in [RFC 628: Prettier](https://emberjs.github.io/rfcs/0628-prettier.html).

**Comment by zg3d** [comment]
Can I help with this issue.

**Comment by jelhan** [comment]
@zg3d That would be great! If it's okay for you, it may be helpful to wait until #158 is merged. It touches many places and I would fear a huge amount of merge conflicts if we do both in parallel. I hope that I can merge it soon.

**Comment by zg3d** [comment]
Alright! I will wait thanks!

**Comment by jelhan** [comment]
@zg3d Seems I can not land #158 as soon as I hoped. Uncovered some other issues with test suite and CI pipeline when running against other Ember CLI versions. Feel free to provide the Prettier merge request as soon as it fits for you. Will rebase my feature branch afterwards if needed.

**Comment by jelhan** [comment]
Closed by #162
