### ISSUE TITLE
Automate dependency upgrades

### ISSUE THREAD

**Issue by jelhan** [rwjblue/ember-cli-content-security-policy#173]
Should use either [Dependabot](https://dependabot.com/) or [RenovateBot](https://github.com/renovatebot/renovate) to automate dependency upgrades. @rwjblue any preferences?

**Comment by rwjblue** [comment]
Both have pros and cons (dependabot is "first party" from GH, but has a massive number of PRs that leads to a bit of noise; RenovateBot is third party, but allows grouping of updates and more granularity RE: scheduling).

I've used both in a few repos, and think either is totally a good choice so ultimately whichever seems more convenient for you is good.

**Comment by jelhan** [comment]
I have a little bit more experience with RenovateBot. Mostly because it's also available on-premise. But I'm also fine with both.

I think in both cases you need to activate it for the repository. Just checked and I don't seem to have the permissions for either of them. Would be great if you could do so. I can take over from there.

**Comment by rwjblue** [comment]
I enabled Dependabot (sorry if that is more annoying, I didn't know how to do Renovate initial setup):

* monthly updates
* auto-merge in range updates
* increase version ranges always

**Comment by jelhan** [comment]
Thanks a lot!
