### ISSUE TITLE
ember-cli yelling can't load script because it violates csp though I followed the docs on this repo

### ISSUE THREAD

**Issue by mankind** [rwjblue/ember-cli-content-security-policy#19]
I am using ember-cli version 0.1.2 and "ember-cli-content-security-policy": "0.3.0".

I am trying to use stripe but everytime I submit  a request to stripe and get a response, Ember-cli will yell at me with: 

     [Report Only] Refused to load the script 'https://api.stripe.com/v1/tokens?card[number]=76&card[cvc]=90&card[exp_mont…pk_test_omMgQGUbGqdvwpHDg2L2crpm&callback=sjsonp1416392279257&_method=POST' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' localhost:35729 0.0.0.0:35729".

my config.js has:

       contentSecurityPolicy: {
        'default-src': "'none'",
        'script-src': "'self' 'unsafe-eval' http://*:35729 https://api.stripe.com/v1 ",
        'font-src': "'self'",
        'connect-src': "'self' http://*:35729 https://api.stripe.com",
        'img-src': "'self'",
        'style-src': "'self'",
        'media-src': "'self'"
      }

What else do I need to get this working

**Comment by wolfbiter** [comment]
**solution here** for anyone who finds this: https://github.com/firebase/emberfire/issues/175

**Comment by sandstrom** [comment]
I think this issue can be closed. @mankind do you mind closing?
