### ISSUE TITLE
Tests fail after installing this addon because of `ember-cli`

### ISSUE THREAD

**Issue by boris-petrov** [rwjblue/ember-cli-content-security-policy#199]
`ember-cli` adds a script tag (see [here](https://github.com/ember-cli/ember-cli/blob/v3.26.1/lib/utilities/ember-app-utils.js#L132)) when running tests. This fails the tests unless one adds `unsafe-inline` to `script-src`. What are we supposed to do about that? I guess that should be fixed in `ember-cli`?

**Comment by jelhan** [comment]
What version of `ember-cli-content-security-policy` are you using? The addon should whitelist that script tag automatically. A fix for Ember CLI >=3.25.1 was just released a few days ago as `v2.0.0-3`. Please note that it is a prerelease.

**Comment by boris-petrov** [comment]
@jelhan - thanks for the support!

I should have been more explicit, sorry about that. I'm talking about the latest prerelase version of `ember-cli-content-security-policy` - `v2.0.0-3` and latest stable `ember-cli` - `3.26.1`.

It's actually trivial to reproduce:

```bash
ember new ember-cli-content-security-policy-bug
cd ember-cli-content-security-policy-bug
ember install ember-cli-content-security-policy
ember test -s
```

And check the HTML - there is the `script` tag without a `nonce`. It is strange that the [code](https://github.com/snewcomer/ember-cli-content-security-policy/blob/master/index.js#L310) checks for `Ember.assert` but in the generated code from `ember-cli` there [is no such thing](https://github.com/ember-cli/ember-cli/blob/v3.26.1/lib/utilities/ember-app-utils.js#L132)?

**Comment by jelhan** [comment]
It seems as if the code, which we are trying to rewrite, has changed a lot in the last Ember CLI releases.

This is how it looks like for different versions of Ember CLI:

- >= 3.26.0
   ```html
   <script>
   document.addEventListener('DOMContentLoaded', function() {
     if (!EmberENV.TESTS_FILE_LOADED) {
       throw new Error('The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js".');
     }
   });
   </script>
   ```
   https://github.com/ember-cli/ember-cli/blob/v3.26.0/lib/utilities/ember-app-utils.js#L132-L138

- >= 3.25.1 && < 3.26.0
  ```html
  <script>document.addEventListener('DOMContentLoaded', function() { Ember.assert('The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js".', EmberENV.TESTS_FILE_LOADED);});</script>
   ```
   https://github.com/ember-cli/ember-cli/blob/v3.25.1/lib/utilities/ember-app-utils.js#L131-L133

- <= 3.25.0
   ```html
   <script>Ember.assert('The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js".', EmberENV.TESTS_FILE_LOADED);</script>
   ```
   https://github.com/ember-cli/ember-cli/blob/v3.25.0/lib/utilities/ember-app-utils.js#L131-L133

@snewcomer added support for Ember CLI >= 3.25.1 <= 3.26.0 in #197. I guess we need a similar hot fix for Ember CLI >= 3.26.0. @boris-petrov do you have time to work on such a hotfix?

A long-term strategy, which would not require hard-coding a regular expression for Ember CLI and would also support similar use cases from other addons is discussed in #149.

I'm a little bit concerned that the tests are not failing if run with Ember CLI 3.26.1. There is a test, which should verify that tests are passing for a newly created Ember application: https://github.com/rwjblue/ember-cli-content-security-policy/blob/93924fa54dd472de89ea0b0f5d1f126c40758c9a/node-tests/e2e/test-support-test.js#L69-L75 Will have a look what is going on there.

**Comment by snewcomer** [comment]
I can try fixing in #198 if that is ok with you!  Or if Boris already has a fix in place, that is fine with me to.

**Comment by boris-petrov** [comment]
@snewcomer - go ahead, I haven't worked on this.

@jelhan - a new Ember app with all the latest versions does pass the tests, yes. I think it's because for some reason the handler for a CSP violation is not registered - even if I put `failTests: true`. I didn't dig into why - as looking in the HTML one could see the `script` tag from `ember-cli` has no `nonce`. But yes, if you have tests for that, they should be made to fail.

**Comment by rwjblue** [comment]
Shoot, sorry for breaking this again @jelhan 🤦
