### ISSUE TITLE
List policies in a list instead of a long string

### ISSUE THREAD

**Issue by unwiredbrain** [rwjblue/ember-cli-content-security-policy#21]
Following the suggestion received on PR #15 I'm now opening this issue to track the development of this discussion.

@givanse [suggested](https://github.com/rwjblue/ember-cli-content-security-policy/pull/15#issue-46017797) using an array of strings to represent the single CSP rule — this allows to programmatically manipulate the various rules.

@rwjblue [liked the idea](https://github.com/rwjblue/ember-cli-content-security-policy/pull/15#issuecomment-59416397) and mentioned the fact that we'd probably better define a deprecation path.

[I added](https://github.com/rwjblue/ember-cli-content-security-policy/pull/15#issuecomment-61302427) that maybe we could use `csp:` schema-prefixed keywords so that there's no need to mix single quotes (`'`) and double quotes (`"`) and to allow, once more, programmability.

**Comment by sir-dunxalot** [comment]
I think the more it's aligned with the CSP spec the better. Using a `csp:` prefix seems like an unnecessary addition that people won't understand. I think I'd prefer to see the keywords entered as CSP expects - strings surrounded by quotes. The mix of single and double quotes is not ideal but more familiar to developers than a new prefix that's not in the specification.

The alternative would be to hardcode the keywords and let the developer enter everything as a string. For example:

```
['self', 'https://somedomain.com']
```

This addon would then add the quotes around the keywords. Again, that seems like a step away from the spec that this addon is trying to support though.

**Comment by unwiredbrain** [comment]
@rwjblue any thoughts?

**Comment by buschtoens** [comment]
I'm very much in favor of using a list / array interface instead of the current string interface. This really eases the pain of having to provide different protocols (`http` vs `https`) for development and production.

I also like the keyword transformation suggested by @sir-dunxalot. This makes for a very clear interfaces.
