### ISSUE TITLE
how to handle data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=

### ISSUE THREAD

**Issue by granteagon** [rwjblue/ember-cli-content-security-policy#25]
I am not sure how to add this to my CSP.  I have tried it in many forms and it always breaks my CSP rule when I add it.

My CSP:
```js
contentSecurityPolicy: {
      'img-src': "'self' *.tile.osm.org data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
      'script-src': "'self' 'unsafe-eval' localhost:35729 0.0.0.0:35729 demo3.mysite.com",
      'connect-src': "'self' ws://localhost:35729 ws://0.0.0.0:35729 demo3.mysite.com"
    }
```

Console error (if I remove the data:image clause):
```
[Report Only] Refused to load the image 'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=' because it violates the following Content Security Policy directive: "img-src 'self' *.tile.osm.org".
```

**Comment by sir-dunxalot** [comment]
[content-security-policy.com](http://content-security-policy.com/) and [MDN](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#Data) both say `data:` should allow resource loading via the data scheme.

`'img-src': "'self' data:"` doesn't work with this addon. That would suggest this is a bug.

**Comment by granteagon** [comment]
Just did a test.  I was missing the trailing colon on data.  `data:*` and `'data'` both fail, but plain `data:` does work.  For anyone stumbling on this thread, here is my working content security policy for images:
```
'img-src': "'self' *.tile.osm.org *.tiles.mapbox.com data:",
```

**Comment by Voles** [comment]
`data:` works, thanks!

````
contentSecurityPolicy: {
    'img-src': "'self' data:"
  }
````

**Comment by sir-dunxalot** [comment]
@granteagon Maybe close this issue?

**Comment by sandstrom** [comment]
@granteagon would you mind closing this issue? :boat:

**Comment by granteagon** [comment]
Sorry guys, missed this notification.

**Comment by complanboy2** [comment]
As for chrome extension manifest, the above suggestion working. Thanks guys.

`"content_security_policy": "script-src 'self' https://ssl.google-analytics.com; object-src 'self'; img-src: 'self' data:"`
