### ISSUE TITLE
Thoughts on transferring to ember-cli org

### ISSUE THREAD

**Issue by stefanpenner** [rwjblue/ember-cli-content-security-policy#26]
Not a all required, if you are interested ember-cli org now exists now and as this repo provides core functionality you are welcome to transition it to that org.

I will be sure you continue to maintain existing commits + ownership.

If at this point in time you would prefer not to, this is fine. But if in the future you no-longer want to maintain this project, I will then gladly welcome it on the org.

**Comment by rwjblue** [comment]
Closing for now (since this is not a default included addon), but I'm happy to migrate to ember-cli if you want to still...
