### ISSUE TITLE
SVG (or possibly all object tags) still cause report-uri error

### ISSUE THREAD

**Issue by jfelchner** [rwjblue/ember-cli-content-security-policy#29]
The `report-uri` fix that is currently on `master` seems to only partially work.

When adding SVG images to the page via an `object` tag:

```html
<object class="header-icon" data="images/my-svg-image.svg" width="40"  height="23" type="image/svg+xml"></object>
```

the following error is shown in console:

> The Content Security Policy 'default-src 'none'; connect-src 'self' ws://localhost:35729 ws://0.0.0.0:35729; font-src 'self' https://fonts.gstatic.com; frame-src 'self'; img-src 'self'; media-src 'self'; object-src 'self'; script-src 'self' localhost:35729 0.0.0.0:35729; style-src 'self' http://fonts.googleapis.com https://fonts.googleapis.com;' was delivered in report-only mode, but does not specify a 'report-uri'; the policy will have no effect. Please either add a 'report-uri' directive, or deliver the policy via the 'Content-Security-Policy' header.

The source line for that error is:

`images/my-svg-image.svg:1`

**Comment by tolgaek** [comment]
@jfelchner Have you figured this issue out, we have this issue only with Safari

**Comment by sandstrom** [comment]
I think this issue can be closed, since it's not an issue with this addon (rather a browser issue). @jfelchner do you mind closing?
