### ISSUE TITLE
Build hangs under iojs

### ISSUE THREAD

**Issue by ZebraFlesh** [rwjblue/ember-cli-content-security-policy#32]
It looks like this code doesn't build under any version of iojs; running `ember build` causes the process to hang (and peg the CPU depending on the version of iojs).  I started with the latest (1.8.1) and then cherry picked my way back to 1.0.0, all with the same result.  I used nvm so I was always getting the correct iojs/npm pair.  I'm running on OS X 10.10.3.

This is totally weird and I've never seen this sort of thing before. The build works fine under node.js 0.12.2.

**Comment by ZebraFlesh** [comment]
Hmm is this maybe related to AvianFlu/ncp#79 meaning this project needs a minimum ember-cli version of 0.1.10 to run on iojs?

**Comment by rwjblue** [comment]
Yes, `ncp` was incorrectly detecting the platform version.  You must use a more recent ember-cli (I would highly suggest "latest")...

**Comment by ZebraFlesh** [comment]
Thanks, I'll do a pull request later this week to upgrade this project to ember-cli 0.2.3 then.
