### ISSUE TITLE
Minor Spelling Mistake

### ISSUE THREAD

**Issue by jayden-leuciuc** [rwjblue/ember-cli-content-security-policy#324]
Noticed just a small mistake in the auto import section:
"[Ember Auto Import](https://github.com/ef4/ember-auto-import#ember-auto-import) uses the eval function by default in development builds. This violates the default CSP policy. It's recommended to set Ember Auto Import's forbidEval option to true if using Content Security Policy. You should not add 'unsafe-eval' to script-src directive as this **disalbes** main security provided by CSP."
`disalbes` -> `disables`

**Comment by jelhan** [comment]
Good catch. Thanks for reporting.

Do you have time to create a pull request fixing it?

**Comment by jayden-leuciuc** [comment]
I had some issues pushing the code. I cloned the repo, created my branch, but whenever I pushed my code I get a 403 error. Sorry, this is my first time contributing to an outside project.

**Comment by jelhan** [comment]
@jayden-leuciuc You need to fork the repository, apply the changes to a feature branch on your fork and create a merge request from the feature branch of your fork against main branch of this repository to propose the changes upstream. It is described here in detail: https://docs.github.com/en/get-started/quickstart/fork-a-repo

**Comment by jelhan** [comment]
Fixed via #325
