### ISSUE TITLE
CSP reporter does not work on windows

### ISSUE THREAD

**Issue by ZebraFlesh** [rwjblue/ember-cli-content-security-policy#36]
During normal local development, the report-uri is computed as http://0.0.0.0:4200/csp-report.  On unix based systems (including OS X), this is not a problem and the 0.0.0.0 is properly resolved to localhost or some equivalent.  On Windows, the POST fails completely and CSP report is never logged to the console.  Windows just doesn't like this address.

**Comment by rwjblue** [comment]
I am unsure if we should just hard-code to http://localhost (likely not), but we may have to do something similar to https://github.com/ember-cli/ember-cli/pull/3386: use `localhost:<port-number>` if no `--host` was specified or the `--host` if it was specified.

**Comment by ZebraFlesh** [comment]
As a temporary work around, if you run `ember serve --host localhost` it looks like the correct value will be picked up on Windows. Kind of annoying and not exactly obvious though.
