### ISSUE TITLE
Firefox Inspector violates directive style-src

### ISSUE THREAD

**Issue by AW-UC** [rwjblue/ember-cli-content-security-policy#40]
Using the Inspector on Firefox causes a CSP violation. This might be related to #38. I already applied https://github.com/ZebraFlesh/ember-cli-content-security-policy/commit/b851c055fa2f58dbe1d8a4d1ee9db6e5fabe498b, but that does only concern `script-src`. Steps to reproduce:
* On Windows (7) generate a new Ember app (latest ember-cli) and start: `ember serve --host localhost`
* With latest stable Firefox browse to `http://localhost:4200/`
* Open the inspector and play around with the selector and page elements
* you will get CSP reports. They might not be shown in the console, but they'll appear in the network tab and in the console output of `ember serve`
The CSP reports will be similar to:
```json
{"csp-report":{
  "blocked-uri":"self",
  "document-uri":"http://localhost:4200/",
  "original-policy":
    "default-src 'none'; 
     script-src http://localhost:4200 'unsafe-eval' http://localhost:35729 http://0.0.0.0:35729; 
     font-src http://localhost:4200; 
     connect-src http://localhost:4200 ws://localhost:35729 ws://0.0.0.0:35729 http://localhost:4200/csp-report; 
     img-src http://localhost:4200; 
     style-src http://localhost:4200; 
     media-src http://localhost:4200; 
     report-uri http://localhost:4200/csp-report",
  "referrer":"",
  "script-sample":"width:100%;height:100%;",
  "source-file":"http://localhost:4200/",
  "violated-directive":"style-src http://localhost:4200"
}}
```

**Comment by Eptis** [comment]
This also happens on Mac OSX Firefox version 37. Can be reproduced in the same way.

**Comment by sandstrom** [comment]
@AW-UC Is this still around? 

I tried to reproduce on FF 41 just now but couldn't (but I may have missed it somehow).

**Comment by AW-UC** [comment]
@sandstrom I can't reproduce this one anymore on latest FF. Thus, closing this. However, #38 is still present.
