### ISSUE TITLE
Default settings don't work in Safari

### ISSUE THREAD

**Issue by mike-post** [rwjblue/ember-cli-content-security-policy#48]
Using ember-cli 1.13.6, generate a new application and run `ember serve`. Load the page in Chrome and Firefox, no CSP violations. Load the page in Safari 8.0.7 and you get: `[Error] [Report Only] Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". (localhost, line 0)`

So far I haven't been able to crack this one. :(

**Comment by bthomas14** [comment]
+1

**Comment by sandstrom** [comment]
Tried to reproduce but could not. Might this be due to a Safari plugin? I'll close this issue now, but happy to reopen if more details are found.
