### ISSUE TITLE
No CORS headers set on 404 responses

### ISSUE THREAD

**Issue by metz0r** [rwjblue/ember-cli-content-security-policy#52]
Normal request: 
Request Method:GET
Status Code:200 OK

Response:
Access-Control-Allow-Origin: http://localhost:4300

404 request:
Request Method:GET
Status Code:404 Not Found

(no Access-Control-Allow-Origin here)

This makes it hard to debug 404 pages when developing locally. Any ideas on how to fix this?

**Comment by sandstrom** [comment]
It sounds like this is about [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) and not about [CSP](https://developer.mozilla.org/en-US/docs/Web/Security/CSP) (which this addon concerns).

I'll close this issue for now, but please let me know if you think it should be reopened.
