### ISSUE TITLE
connect-src not properly inheriting from default-src

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-cli-content-security-policy#61]
Given the following:

```
    contentSecurityPolicy: {
      'default-src': ["'self'", "*.foo.com"]
    }
```

I receive the following CSP report:

> [Report Only] Refused to connect to 'https://bar.foo.com/thingy' because it violates the following Content Security Policy directive: "connect-src 'self' ws://localhost:49152 ws://0.0.0.0:49152 http://localhost:4200".

I would have expected https://github.com/rwjblue/ember-cli-content-security-policy/pull/57 to address this, but it seems that we are missing something still...

**Comment by sandstrom** [comment]
@rwjblue You are right, it should have. I can look into it! Do you have a repo that reproduces this? (or a bin)
