### ISSUE TITLE
Hanging phantomjs during testing

### ISSUE THREAD

**Issue by devinus** [rwjblue/ember-cli-content-security-policy#63]
https://github.com/ember-cli/ember-cli/issues/5415

This is still a problem after trying to upgrade everything in my app.

**Comment by devinus** [comment]
I've narrowed it down to this reason:

> Refused to frame 'http://localhost:7357/testem/connection.html' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by sandstrom** [comment]
@devinus Thanks for investigating! ⛵ 

Presumably the default policy must be more permissive when running the tests. If you can figure out some adjustments that make it work I'll be happy to adjust the code accordingly.

If you change the policy to allow `frame-src: localhost:7357` by default, is that enough to make the tests run?

**Comment by devinus** [comment]
`frame-src: 'self'` is what's needed to make them run. Perhaps adding `frame-src` to the defaults would be good? If https://github.com/rwjblue/ember-cli-content-security-policy/issues/64#issuecomment-216360737 is fixed I could make it report only during testing since I use the meta tag version.

**Comment by sandstrom** [comment]
@devinus thanks!

Does an adjustment like this work?

```js
// index.js
config: function(environment /* appConfig */) {
  let header = CSP_HEADER_REPORT_ONLY;

  let policy = {
    'default-src':  [CSP_NONE],
    'script-src':   [CSP_SELF],
    'font-src':     [CSP_SELF],
    'connect-src':  [CSP_SELF],
    'img-src':      [CSP_SELF],
    'style-src':    [CSP_SELF],
    'media-src':    [CSP_SELF],
  };

  if (environment === 'test') {
    policy['frame-src'] = CSP_SELF;
  }
  
  return ({
    contentSecurityPolicyHeader: header,
    contentSecurityPolicy: policy,
  });
},
```

**Comment by devinus** [comment]
@sandstrom I think so.

**Comment by sandstrom** [comment]
@devinus Would you like to try it out and let me know how it goes? Ideally also in the context of https://github.com/ember-cli/ember-cli/issues/5415

If so I'll make the necessary changes.

**Comment by devinus** [comment]
@sandstrom This works.

**Comment by sandstrom** [comment]
@devinus I've patched it here https://github.com/rwjblue/ember-cli-content-security-policy/pull/65 (you can use the branch in the interim, until this lands in master).

Thanks for helping me verify and solve this issue!
