### ISSUE TITLE
Meta option ignores contentSecurityPolicyHeader option

### ISSUE THREAD

**Issue by devinus** [rwjblue/ember-cli-content-security-policy#64]
The http-equiv will always be `Content-Security-Policy`.

**Comment by sandstrom** [comment]
Please tell me more, what behaviour would you like to see instead?

Afaik a `<meta ...>` tag with a `http-equiv` value other than `Content-Security-Policy` doesn't make any sense. But I'm happy to hear your thoughts on this!

**Comment by devinus** [comment]
`Content-Security-Policy-Report-Only` if that's what `contentSecurityPolicyHeader` is set to. The meta option is just a different way to use this plugin. Sometimes I want it to be Report Only on my e.g. dev or staging environment.

**Comment by sandstrom** [comment]
It's not part of the spec, unfortunately (I wish it were!).

> Note: The Content-Security-Policy-Report-Only header is not supported inside a meta element. Neither are the report-uri, frame-ancestors, and sandbox directives.
> 
> https://w3c.github.io/webappsec-csp/#meta-element

**Comment by sandstrom** [comment]
I'm closing this, since per the spec the `http-equiv` value is static.
