### ISSUE TITLE
Remove X- headers

### ISSUE THREAD

**Issue by maletor** [rwjblue/ember-cli-content-security-policy#66]
From the http://content-security-policy.com/ website.

> Note: It is known that having both Content-Security-Policy and X-Content-Security-Policy or X-Webkit-CSP causes unexpected behaviours on certain versions of browsers. Please avoid using deprecated X-* headers.

What do you make of this?

**Comment by sandstrom** [comment]
This mainly concerns IE 11 (which is still using X-Content-Security-Policy):
http://caniuse.com/#feat=contentsecuritypolicy

@maletor Have you had issues because of this? If so, under which circumstances?

**Comment by maletor** [comment]
I have not, but I thought I'd bring it to your attention. I will have to investigate what is meant by "causes unexpected behaviors" more in depth.

> (I'd love for IE to just disappear, but unfortunately it'll be around for a while)

Amen.

**Comment by sandstrom** [comment]
@maletor Sounds good! Thanks for highlighting this.

I'll close this issue for now, but happy to reopen later if you find more details.
