### ISSUE TITLE
Sample policy is vulnerable to bypass attacks

### ISSUE THREAD

**Issue by philippederyck** [rwjblue/ember-cli-content-security-policy#69]
The sample policy given in the readme is vulnerable to bypass attacks, as it whitelists an enitre CDN. More information: https://speakerdeck.com/mikispag/making-csp-great-again-michele-spagnuolo-and-lukas-weichselbaum

**Comment by rwjblue** [comment]
Thanks for mentioning this, I would happily accept a PR fixing.

**Comment by sandstrom** [comment]
@philippederyck I agree that CSP can be vulnerable if misconfigured, and happy to hear any suggestions on improving the readme and documentation around vulnerabilities.

While we probably won't be the authoritative source on CSP we'll happy link to useful resources.

That said, I'm not certain the example is vulnerable. Which CDN are you thinking about? Afaik Mixpanel's CDN doesn't do JSONP.

**Comment by philippederyck** [comment]
@rwjblue I will try to get something together next week. I'll keep you posted

@sandstrom Whitelisting an entire CDN for a script-src is a bad idea, for example because it allows the attacker to load an older AngularJS library, and insert malicious script that will be processed by angular, without triggering CSP violations (e.g. slide 17 and 18 in the deck I referenced). 

I didn't check if the CDN actually hosts Angular or not, but either way, I think it's better to give a more locked down policy. I just wanted to point this out, since it's not unlikely that people will take this code as an example.

**Comment by sandstrom** [comment]
@philippederyck I've tightened up the example: 6189255a6513d09507411cdd9b692d7b0508d787

Also added a reference to the [research paper](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/45542.pdf) that spurred this discussion (same author as the slides you linked).

Let me know if you have further suggestions!

**Comment by sandstrom** [comment]
@philippederyck would you like to add something here? Otherwise I'll go ahead and close this issue.

Thanks for pointing this out, it helped us tighten up the example policy.

**Comment by philippederyck** [comment]
Hi @sandstrom , sorry for the late response, I was out of the office for a few days. Seems to be OK to me, thanks for fixing it!
