### ISSUE TITLE
update ember-cli-babel to solve minimatch deprecation

### ISSUE THREAD

**Issue by sureshprasanna70** [rwjblue/ember-cli-content-security-policy#74]
`ember-cli-babel@5.2.4` is one of the dependency and has `minimatch@2.0.10` as its dependency.Please update `ember-cli-babel` to reflect the update, as `minimatch@2.0.10` has a well known serious RegExp flaw.

**Comment by rwjblue** [comment]
Would love PR to update this to latest ember-cli blueprint.

**Comment by sandstrom** [comment]
Fixed by https://github.com/rwjblue/ember-cli-content-security-policy/pull/78
