### ISSUE TITLE
Difficult to extract a usable CSP using csp-headers command

### ISSUE THREAD

**Issue by jasnross-bt** [rwjblue/ember-cli-content-security-policy#81]
We are working on automating our CSP generation during deployment and ran into a couple of small usability issues that I wanted to report to see what your take is on this kind of thing.

1. Since the `ember csp-headers` command writes the CSP to `stderr`, we end up having to strip out any potential deprecation warnings from the output in order to get a valid CSP extracted:

*Sample output:*
```
$ ember csp-headers
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-data`
    at Function.Addon.lookup (/Users/jasonr/FrontEnd/node_modules/ember-cli/lib/models/addon.js:1617:27)
# Content Security Policy Header Configuration
#
# for Apache: Header set Content-Security-Policy "..."
# for Nginx : add_header Content-Security-Policy "...";

default-src self;
```

2. Additionally, even if the output was to be moved to `stdout` instead of `stderr`, we would still need to strip out the preceding instructional content:

```
# Content Security Policy Header Configuration
#
# for Apache: Header set Content-Security-Policy "..."
# for Nginx : add_header Content-Security-Policy "...";
```

### Proposal:

1. Ensure the resulting CSP content is written to `stdout` instead of `stderr`
2. Add a flag to suppress the instructional content (or move the instructional content to `--help` instead of always outputting it during csp generation)

Perhaps something like this:

```
$ ember csp-headers --csp-only
default-src self;
```

This way the output is easily pipeable into other scripts, readable from childProcess.exec, and generally just ready to be used as soon as it is returned to the caller.

Thanks for looking :) I can probably take a stab at it sometime soon if you agree that a change like this is desirable.

**Comment by sandstrom** [comment]
@jasnross-bt Both of them are good points! 👍 

Happy to review a PR (either one per item above, or a single PR with separate commits for the two issues you've outlined).
