### ISSUE TITLE
Add "worker-src" to policies

### ISSUE THREAD

**Issue by dogindot** [rwjblue/ember-cli-content-security-policy#93]
Report `...because it violates the following Content Security Policy directive: "worker-src 'none'"` is thrown.

**Comment by jelhan** [comment]
It should be straightforward to add additional directives to policy object. If a directive is missing it falls back to `default-src` as described in CSP spec. So I guess `default-src` is `'none'` in your case and you didn't included a `worker-src` directive, isn't it?

**Comment by rwjblue** [comment]
I think its fine to add `worker-src` support here though. I wonder if we should allow arbitrary keys in the configuration object, invalid ones will get a warning in the browser already...

**Comment by sandstrom** [comment]
@rwjblue that's already the case, i.e. we do allow arbitrary keys in the configuration object.

**Comment by sandstrom** [comment]
@dogindot What you want is possible, simply add `'worker-src'` as a key in the configuration, just like any other CSP directive.

```
    // …
    'media-src':   ["'self'"],
    'worker-src':  ["*"],
```


I'm closing this now, but I'm happy to reopen if there is an actual code issue. If so, steps to reproduce (and ideally a failing test-case) is a good start.
