### ISSUE TITLE
Policy object should not be merged but replaced by application configuration

### ISSUE THREAD

**Issue by jelhan** [rwjblue/ember-cli-content-security-policy#99]
Currently the default policy object is merged with application configuration. This is confusing and is likely causing misconfiguation.

Lets assume someone tries to forbid any external assets. So he aims for a CSP Header as following:

```http
Content-Security-Policy: default-src 'none';
```

He would most likely try a configuration as following:

```js
let app = new EmberApp(defaults, {
  'ember-cli-content-security-policy': {
     policy: {
       'default-src': ["'none'"]
     }
  }
});
```

But that would result in the following CSP Header as it's merged with default policy object:

```
Content-Security-Policy: default-src 'none'; script-src 'self'; font-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self'; media-src 'none';
```

In order to achieve the goal this configuration is needed:

```js
let app = new EmberApp(defaults, {
  'ember-cli-content-security-policy': {
     policy: {
       'default-src': ["'none'"],
       'script-src':  null,
       'font-src':    null,
       'connect-src': null,
       'img-src':     null,
       'style-src':   null,
       'media-src':   null,
     }
  }
});
```

This is mentioned in README but easy to be missed:

> To clear a directive from the default policy, set it to `null`.

The general refactoring of configuration done in #94 and #97 is a perfect time to change this in my opinion.

Having the policy object been merged might not have been a clear decision but might likely be caused by implementation details of Ember CLI's `config` hook.

Please note that the merging described here is currently broken in master due to #94. It will be fixed with #97, which also adds tests for this one. We would still need to support it for legacy run time configuration option `contentSecurityPolicy` to not add a breaking change.

**Comment by sandstrom** [comment]
Do we have any reports from users about this causing misconfiguration issues?

I don't mind changing without knowing what users prefer (and if we'd redesign this from scratch I think what you're suggesting may be slightly better, i.e. no merging). 

So I'm mildly 👍 on this without knowing if this is a common problem or not. And if it is, I definitely don't mind dropping the merging.

**Comment by jelhan** [comment]
> Do we have any reports from users about this causing misconfiguration issues? Or what users would prefer?

I've looked through issues and PRs in this repo. Haven't found any discussion mentioning this behavior explicitly. But I think someones are indirectly caused by this:

* #76 shows that there are use cases in which you like to alter `default-src` and being forced to exclude all other ones manually.
* #73 and #93 are asking about adding a `worker-src` directive. Both seem to be motivated by the wrong assumption that directives in default policy could only be altered in application configuration but not additional ones added.

I guess altering `default-src` or trying to make default configuration even stricter is not a common pattern.

My main motivation is reducing the magic around this plugin and it's configuration. It would be great if a developer would know CSP used by looking in application configuration only. This is especially important for a configure and forget thing like CSP and if it's security related IMO.

**Comment by rwjblue** [comment]
IMHO, this is a "security by default" issue. The merging behaviors here _may_ result in incorrect CSP settings (hard to say, and I've not _personally_ had this issue) that are less restrictive than the user intended. This seems not ideal...

I think removing the merging behavior but keeping a "good default" (either by blueprinting it into the consuming app upon installation or by using a built in default when no config is provided by the user) is probably a decent compromise.
